/// Maps crop names to their representative emoji icons.
/// Used in market screen, dashboard briefing, and anywhere crops are listed.
class CropIconService {
  /// Get the emoji icon for a given crop name (English).
  static String getEmoji(String cropName) {
    final key = cropName.toLowerCase().trim();
    return _cropEmojis[key] ?? '🌱';
  }

  static const Map<String, String> _cropEmojis = {
    // ── Grains & Cereals ──
    'wheat': '🌾',
    'corn': '🌽',
    'maize': '🌽',
    'rice': '🍚',
    'barley': '🌾',
    'oats': '🌾',
    'rye': '🌾',
    'millet': '🌾',
    'sorghum': '🌾',
    'buckwheat': '🌾',
    'quinoa': '🌾',
    'spelt': '🌾',
    'triticale': '🌾',

    // ── Vegetables ──
    'tomato': '🍅',
    'potato': '🥔',
    'onion': '🧅',
    'garlic': '🧄',
    'carrot': '🥕',
    'cucumber': '🥒',
    'pepper': '🌶️',
    'bell pepper': '🫑',
    'eggplant': '🍆',
    'broccoli': '🥦',
    'cabbage': '🥬',
    'lettuce': '🥬',
    'spinach': '🥬',
    'celery': '🥬',
    'cauliflower': '🥦',
    'zucchini': '🥒',
    'pumpkin': '🎃',
    'squash': '🎃',
    'sweet potato': '🍠',
    'beet': '🥕',
    'beetroot': '🥕',
    'radish': '🥕',
    'turnip': '🥕',
    'pea': '🫛',
    'green bean': '🫘',
    'asparagus': '🌿',
    'artichoke': '🌿',
    'leek': '🧅',
    'okra': '🌿',
    'mushroom': '🍄',
    'ginger': '🫚',

    // ── Fruits ──
    'apple': '🍎',
    'pear': '🍐',
    'grape': '🍇',
    'orange': '🍊',
    'lemon': '🍋',
    'lime': '🍋',
    'banana': '🍌',
    'watermelon': '🍉',
    'melon': '🍈',
    'strawberry': '🍓',
    'blueberry': '🫐',
    'cherry': '🍒',
    'peach': '🍑',
    'apricot': '🍊',
    'plum': '🍇',
    'fig': '🍐',
    'pomegranate': '🍎',
    'mango': '🥭',
    'pineapple': '🍍',
    'coconut': '🥥',
    'kiwi': '🥝',
    'avocado': '🥑',
    'olive': '🫒',
    'date': '🌴',
    'persimmon': '🍊',
    'quince': '🍐',
    'mulberry': '🍇',
    'cranberry': '🍒',
    'raspberry': '🍓',
    'blackberry': '🍇',
    'currant': '🍒',
    'gooseberry': '🍏',
    'passion fruit': '🥭',
    'papaya': '🥭',
    'guava': '🍏',
    'lychee': '🍒',
    'dragon fruit': '🥝',
    'tangerine': '🍊',
    'mandarin': '🍊',
    'grapefruit': '🍊',
    'clementine': '🍊',
    'nectarine': '🍑',

    // ── Nuts ──
    'almond': '🌰',
    'walnut': '🌰',
    'hazelnut': '🌰',
    'pistachio': '🌰',
    'peanut': '🥜',
    'cashew': '🌰',
    'chestnut': '🌰',
    'pecan': '🌰',
    'macadamia': '🌰',
    'brazil nut': '🌰',
    'pine nut': '🌰',

    // ── Industrial Crops ──
    'cotton': '☁️',
    'tobacco': '🍂',
    'sugarcane': '🍬',
    'sugar beet': '🍬',
    'sugar': '🍬',
    'tea': '🍵',
    'coffee': '☕',
    'cocoa': '🍫',
    'rubber': '🌳',
    'hemp': '🌿',
    'flax': '🌿',
    'jute': '🌿',

    // ── Oil Crops ──
    'sunflower': '🌻',
    'soybean': '🫘',
    'rapeseed': '🌻',
    'canola': '🌻',
    'palm oil': '🌴',
    'sesame': '🌻',
    'safflower': '🌻',
    'castor': '🌻',
    'linseed': '🌻',
    'mustard': '🌻',

    // ── Legumes ──
    'lentil': '🫘',
    'chickpea': '🫘',
    'bean': '🫘',
    'fava bean': '🫘',
    'kidney bean': '🫘',
    'black bean': '🫘',
    'mung bean': '🫘',
    'pigeon pea': '🫘',
    'cowpea': '🫘',
    'lupine': '🫘',

    // ── Spices & Herbs ──
    'saffron': '🌸',
    'cumin': '🌿',
    'coriander': '🌿',
    'turmeric': '🌿',
    'cinnamon': '🌿',
    'clove': '🌿',
    'cardamom': '🌿',
    'vanilla': '🌿',
    'black pepper': '🌶️',
    'paprika': '🌶️',
    'chili': '🌶️',
    'mint': '🌿',
    'basil': '🌿',
    'oregano': '🌿',
    'thyme': '🌿',
    'rosemary': '🌿',
    'parsley': '🌿',
    'dill': '🌿',
    'fennel': '🌿',
    'anise': '🌿',
    'bay leaf': '🍃',

    // ── Citrus ──
    'citrus': '🍊',

    // ── Flowers ──
    'rose': '🌹',
    'lavender': '💜',
    'tulip': '🌷',
    'carnation': '🌸',
    'chrysanthemum': '🌼',

    // ── Other ──
    'honey': '🍯',
    'milk': '🥛',
    'egg': '🥚',
    'wool': '🧶',
    'silk': '🧵',
    'hops': '🍺',
  };
}
